# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 720b2072b9df1b0f4d4ed1bbc74a08ee343940bc84b707d368e3c429160d7a9d586624043afa9fa400283a7ef396ddb4a35c9d5f4457c38759d75a704c109d25

test:
  secret_key_base: 0e6f7449fc618be2086c9100758400f64ae5f7f62bba637a8a41232385834d758818339f567409529904f1bfd58743eb140a1d6df89e24c534af0a7472c0689c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
